name: synwalk
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.4
  - boost=1.70.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.14.12
  - cairomm=1.12.2
  - certifi=2021.5.30
  - cgal=5.0.1
  - cgal-cpp=5.0.1
  - cycler=0.10.0
  - dbus=1.13.14
  - decorator=4.4.2
  - defusedxml=0.6.0
  - eigen=3.3.8
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - graph-tool=2.29
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.1
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.15.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.3
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsigcpp=3.0.3
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - mpfr=4.0.2
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - ncurses=6.2
  - networkx=2.4
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1h
  - pandas=1.0.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.40.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - ptyprocess=0.6.0
  - pycairo=1.19.0
  - pygments=2.6.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=47.1.1
  - sigcpp-3.0=3.0.3
  - sip=4.19.8
  - six=1.15.0
  - sparsehash=2.0.3
  - sqlite=3.31.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.1
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - clusim==0.4
    - mpmath==1.1.0
    - python-igraph==0.8.2
    - texttable==1.6.2
